export const SUPPORTED_LANGUAGES = [
  'English',
  'French',
  'Spanish',
  'Portuguese',
  'Arabic',
  'Swahili',
  'Kinyarwanda',
  'Hausa',
  'Yoruba',
  'Igbo',
  'Twi',
  'Zulu',
  'Afrikaans',
  'Nigerian Pidgin',
  'German',
  'Hindi',
  'Bengali',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Japanese',
  'Korean',
  'Italian',
  'Dutch',
  'Russian',
  'Turkish',
  'Indonesian',
  'Vietnamese',
];
