/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/org.$slug'
import { Route as CatalogSlugRouteImport } from './routes/catalog.$slug'
import { Route as OrgSlugIndexRouteImport } from './routes/org.$slug.index'
import { Route as CatalogSlugIndexRouteImport } from './routes/catalog.$slug.index'
import { Route as OrgSlugTeamRouteImport } from './routes/org.$slug.team'
import { Route as OrgSlugSettingsRouteImport } from './routes/org.$slug.settings'
import { Route as OrgSlugServicesRouteImport } from './routes/org.$slug.services'
import { Route as OrgSlugReportsRouteImport } from './routes/org.$slug.reports'
import { Route as OrgSlugPayoutsRouteImport } from './routes/org.$slug.payouts'
import { Route as OrgSlugInvoicesRouteImport } from './routes/org.$slug.invoices'
import { Route as OrgSlugHelpRouteImport } from './routes/org.$slug.help'
import { Route as OrgSlugExpensesRouteImport } from './routes/org.$slug.expenses'
import { Route as OrgSlugClientsRouteImport } from './routes/org.$slug.clients'
import { Route as OrgSlugBusinessesRouteImport } from './routes/org.$slug.businesses'
import { Route as CatalogSlugCheckoutRouteImport } from './routes/catalog.$slug.checkout'
import { Route as OrgSlugInvoicesIndexRouteImport } from './routes/org.$slug.invoices.index'
import { Route as OrgSlugInvoicesCreateRouteImport } from './routes/org.$slug.invoices.create'
import { Route as CatalogSlugSuccessInvoiceIdRouteImport } from './routes/catalog.$slug.success.$invoiceId'
import { Route as CatalogSlugInvoiceInvoiceIdRouteImport } from './routes/catalog.$slug.invoice.$invoiceId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const CatalogSlugIndexRoute = CatalogSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogSlugRoute,
} as any)
const OrgSlugTeamRoute = OrgSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugServicesRoute = OrgSlugServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugReportsRoute = OrgSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugPayoutsRoute = OrgSlugPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugInvoicesRoute = OrgSlugInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugHelpRoute = OrgSlugHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugExpensesRoute = OrgSlugExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugClientsRoute = OrgSlugClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugBusinessesRoute = OrgSlugBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => OrgSlugRoute,
} as any)
const CatalogSlugCheckoutRoute = CatalogSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CatalogSlugRoute,
} as any)
const OrgSlugInvoicesIndexRoute = OrgSlugInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugInvoicesRoute,
} as any)
const OrgSlugInvoicesCreateRoute = OrgSlugInvoicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrgSlugInvoicesRoute,
} as any)
const CatalogSlugSuccessInvoiceIdRoute =
  CatalogSlugSuccessInvoiceIdRouteImport.update({
    id: '/success/$invoiceId',
    path: '/success/$invoiceId',
    getParentRoute: () => CatalogSlugRoute,
  } as any)
const CatalogSlugInvoiceInvoiceIdRoute =
  CatalogSlugInvoiceInvoiceIdRouteImport.update({
    id: '/invoice/$invoiceId',
    path: '/invoice/$invoiceId',
    getParentRoute: () => CatalogSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/catalog/$slug': typeof CatalogSlugRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/catalog/$slug/checkout': typeof CatalogSlugCheckoutRoute
  '/org/$slug/businesses': typeof OrgSlugBusinessesRoute
  '/org/$slug/clients': typeof OrgSlugClientsRoute
  '/org/$slug/expenses': typeof OrgSlugExpensesRoute
  '/org/$slug/help': typeof OrgSlugHelpRoute
  '/org/$slug/invoices': typeof OrgSlugInvoicesRouteWithChildren
  '/org/$slug/payouts': typeof OrgSlugPayoutsRoute
  '/org/$slug/reports': typeof OrgSlugReportsRoute
  '/org/$slug/services': typeof OrgSlugServicesRoute
  '/org/$slug/settings': typeof OrgSlugSettingsRoute
  '/org/$slug/team': typeof OrgSlugTeamRoute
  '/catalog/$slug/': typeof CatalogSlugIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/catalog/$slug/invoice/$invoiceId': typeof CatalogSlugInvoiceInvoiceIdRoute
  '/catalog/$slug/success/$invoiceId': typeof CatalogSlugSuccessInvoiceIdRoute
  '/org/$slug/invoices/create': typeof OrgSlugInvoicesCreateRoute
  '/org/$slug/invoices/': typeof OrgSlugInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/catalog/$slug/checkout': typeof CatalogSlugCheckoutRoute
  '/org/$slug/businesses': typeof OrgSlugBusinessesRoute
  '/org/$slug/clients': typeof OrgSlugClientsRoute
  '/org/$slug/expenses': typeof OrgSlugExpensesRoute
  '/org/$slug/help': typeof OrgSlugHelpRoute
  '/org/$slug/payouts': typeof OrgSlugPayoutsRoute
  '/org/$slug/reports': typeof OrgSlugReportsRoute
  '/org/$slug/services': typeof OrgSlugServicesRoute
  '/org/$slug/settings': typeof OrgSlugSettingsRoute
  '/org/$slug/team': typeof OrgSlugTeamRoute
  '/catalog/$slug': typeof CatalogSlugIndexRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/catalog/$slug/invoice/$invoiceId': typeof CatalogSlugInvoiceInvoiceIdRoute
  '/catalog/$slug/success/$invoiceId': typeof CatalogSlugSuccessInvoiceIdRoute
  '/org/$slug/invoices/create': typeof OrgSlugInvoicesCreateRoute
  '/org/$slug/invoices': typeof OrgSlugInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/catalog/$slug': typeof CatalogSlugRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/catalog/$slug/checkout': typeof CatalogSlugCheckoutRoute
  '/org/$slug/businesses': typeof OrgSlugBusinessesRoute
  '/org/$slug/clients': typeof OrgSlugClientsRoute
  '/org/$slug/expenses': typeof OrgSlugExpensesRoute
  '/org/$slug/help': typeof OrgSlugHelpRoute
  '/org/$slug/invoices': typeof OrgSlugInvoicesRouteWithChildren
  '/org/$slug/payouts': typeof OrgSlugPayoutsRoute
  '/org/$slug/reports': typeof OrgSlugReportsRoute
  '/org/$slug/services': typeof OrgSlugServicesRoute
  '/org/$slug/settings': typeof OrgSlugSettingsRoute
  '/org/$slug/team': typeof OrgSlugTeamRoute
  '/catalog/$slug/': typeof CatalogSlugIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/catalog/$slug/invoice/$invoiceId': typeof CatalogSlugInvoiceInvoiceIdRoute
  '/catalog/$slug/success/$invoiceId': typeof CatalogSlugSuccessInvoiceIdRoute
  '/org/$slug/invoices/create': typeof OrgSlugInvoicesCreateRoute
  '/org/$slug/invoices/': typeof OrgSlugInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/catalog/$slug'
    | '/org/$slug'
    | '/catalog/$slug/checkout'
    | '/org/$slug/businesses'
    | '/org/$slug/clients'
    | '/org/$slug/expenses'
    | '/org/$slug/help'
    | '/org/$slug/invoices'
    | '/org/$slug/payouts'
    | '/org/$slug/reports'
    | '/org/$slug/services'
    | '/org/$slug/settings'
    | '/org/$slug/team'
    | '/catalog/$slug/'
    | '/org/$slug/'
    | '/catalog/$slug/invoice/$invoiceId'
    | '/catalog/$slug/success/$invoiceId'
    | '/org/$slug/invoices/create'
    | '/org/$slug/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/catalog/$slug/checkout'
    | '/org/$slug/businesses'
    | '/org/$slug/clients'
    | '/org/$slug/expenses'
    | '/org/$slug/help'
    | '/org/$slug/payouts'
    | '/org/$slug/reports'
    | '/org/$slug/services'
    | '/org/$slug/settings'
    | '/org/$slug/team'
    | '/catalog/$slug'
    | '/org/$slug'
    | '/catalog/$slug/invoice/$invoiceId'
    | '/catalog/$slug/success/$invoiceId'
    | '/org/$slug/invoices/create'
    | '/org/$slug/invoices'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/catalog/$slug'
    | '/org/$slug'
    | '/catalog/$slug/checkout'
    | '/org/$slug/businesses'
    | '/org/$slug/clients'
    | '/org/$slug/expenses'
    | '/org/$slug/help'
    | '/org/$slug/invoices'
    | '/org/$slug/payouts'
    | '/org/$slug/reports'
    | '/org/$slug/services'
    | '/org/$slug/settings'
    | '/org/$slug/team'
    | '/catalog/$slug/'
    | '/org/$slug/'
    | '/catalog/$slug/invoice/$invoiceId'
    | '/catalog/$slug/success/$invoiceId'
    | '/org/$slug/invoices/create'
    | '/org/$slug/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  CatalogSlugRoute: typeof CatalogSlugRouteWithChildren
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/catalog/$slug/': {
      id: '/catalog/$slug/'
      path: '/'
      fullPath: '/catalog/$slug/'
      preLoaderRoute: typeof CatalogSlugIndexRouteImport
      parentRoute: typeof CatalogSlugRoute
    }
    '/org/$slug/team': {
      id: '/org/$slug/team'
      path: '/team'
      fullPath: '/org/$slug/team'
      preLoaderRoute: typeof OrgSlugTeamRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/settings': {
      id: '/org/$slug/settings'
      path: '/settings'
      fullPath: '/org/$slug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/services': {
      id: '/org/$slug/services'
      path: '/services'
      fullPath: '/org/$slug/services'
      preLoaderRoute: typeof OrgSlugServicesRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/reports': {
      id: '/org/$slug/reports'
      path: '/reports'
      fullPath: '/org/$slug/reports'
      preLoaderRoute: typeof OrgSlugReportsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/payouts': {
      id: '/org/$slug/payouts'
      path: '/payouts'
      fullPath: '/org/$slug/payouts'
      preLoaderRoute: typeof OrgSlugPayoutsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/invoices': {
      id: '/org/$slug/invoices'
      path: '/invoices'
      fullPath: '/org/$slug/invoices'
      preLoaderRoute: typeof OrgSlugInvoicesRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/help': {
      id: '/org/$slug/help'
      path: '/help'
      fullPath: '/org/$slug/help'
      preLoaderRoute: typeof OrgSlugHelpRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/expenses': {
      id: '/org/$slug/expenses'
      path: '/expenses'
      fullPath: '/org/$slug/expenses'
      preLoaderRoute: typeof OrgSlugExpensesRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/clients': {
      id: '/org/$slug/clients'
      path: '/clients'
      fullPath: '/org/$slug/clients'
      preLoaderRoute: typeof OrgSlugClientsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/businesses': {
      id: '/org/$slug/businesses'
      path: '/businesses'
      fullPath: '/org/$slug/businesses'
      preLoaderRoute: typeof OrgSlugBusinessesRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/catalog/$slug/checkout': {
      id: '/catalog/$slug/checkout'
      path: '/checkout'
      fullPath: '/catalog/$slug/checkout'
      preLoaderRoute: typeof CatalogSlugCheckoutRouteImport
      parentRoute: typeof CatalogSlugRoute
    }
    '/org/$slug/invoices/': {
      id: '/org/$slug/invoices/'
      path: '/'
      fullPath: '/org/$slug/invoices/'
      preLoaderRoute: typeof OrgSlugInvoicesIndexRouteImport
      parentRoute: typeof OrgSlugInvoicesRoute
    }
    '/org/$slug/invoices/create': {
      id: '/org/$slug/invoices/create'
      path: '/create'
      fullPath: '/org/$slug/invoices/create'
      preLoaderRoute: typeof OrgSlugInvoicesCreateRouteImport
      parentRoute: typeof OrgSlugInvoicesRoute
    }
    '/catalog/$slug/success/$invoiceId': {
      id: '/catalog/$slug/success/$invoiceId'
      path: '/success/$invoiceId'
      fullPath: '/catalog/$slug/success/$invoiceId'
      preLoaderRoute: typeof CatalogSlugSuccessInvoiceIdRouteImport
      parentRoute: typeof CatalogSlugRoute
    }
    '/catalog/$slug/invoice/$invoiceId': {
      id: '/catalog/$slug/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/catalog/$slug/invoice/$invoiceId'
      preLoaderRoute: typeof CatalogSlugInvoiceInvoiceIdRouteImport
      parentRoute: typeof CatalogSlugRoute
    }
  }
}

interface CatalogSlugRouteChildren {
  CatalogSlugCheckoutRoute: typeof CatalogSlugCheckoutRoute
  CatalogSlugIndexRoute: typeof CatalogSlugIndexRoute
  CatalogSlugInvoiceInvoiceIdRoute: typeof CatalogSlugInvoiceInvoiceIdRoute
  CatalogSlugSuccessInvoiceIdRoute: typeof CatalogSlugSuccessInvoiceIdRoute
}

const CatalogSlugRouteChildren: CatalogSlugRouteChildren = {
  CatalogSlugCheckoutRoute: CatalogSlugCheckoutRoute,
  CatalogSlugIndexRoute: CatalogSlugIndexRoute,
  CatalogSlugInvoiceInvoiceIdRoute: CatalogSlugInvoiceInvoiceIdRoute,
  CatalogSlugSuccessInvoiceIdRoute: CatalogSlugSuccessInvoiceIdRoute,
}

const CatalogSlugRouteWithChildren = CatalogSlugRoute._addFileChildren(
  CatalogSlugRouteChildren,
)

interface OrgSlugInvoicesRouteChildren {
  OrgSlugInvoicesCreateRoute: typeof OrgSlugInvoicesCreateRoute
  OrgSlugInvoicesIndexRoute: typeof OrgSlugInvoicesIndexRoute
}

const OrgSlugInvoicesRouteChildren: OrgSlugInvoicesRouteChildren = {
  OrgSlugInvoicesCreateRoute: OrgSlugInvoicesCreateRoute,
  OrgSlugInvoicesIndexRoute: OrgSlugInvoicesIndexRoute,
}

const OrgSlugInvoicesRouteWithChildren = OrgSlugInvoicesRoute._addFileChildren(
  OrgSlugInvoicesRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugBusinessesRoute: typeof OrgSlugBusinessesRoute
  OrgSlugClientsRoute: typeof OrgSlugClientsRoute
  OrgSlugExpensesRoute: typeof OrgSlugExpensesRoute
  OrgSlugHelpRoute: typeof OrgSlugHelpRoute
  OrgSlugInvoicesRoute: typeof OrgSlugInvoicesRouteWithChildren
  OrgSlugPayoutsRoute: typeof OrgSlugPayoutsRoute
  OrgSlugReportsRoute: typeof OrgSlugReportsRoute
  OrgSlugServicesRoute: typeof OrgSlugServicesRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRoute
  OrgSlugTeamRoute: typeof OrgSlugTeamRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugBusinessesRoute: OrgSlugBusinessesRoute,
  OrgSlugClientsRoute: OrgSlugClientsRoute,
  OrgSlugExpensesRoute: OrgSlugExpensesRoute,
  OrgSlugHelpRoute: OrgSlugHelpRoute,
  OrgSlugInvoicesRoute: OrgSlugInvoicesRouteWithChildren,
  OrgSlugPayoutsRoute: OrgSlugPayoutsRoute,
  OrgSlugReportsRoute: OrgSlugReportsRoute,
  OrgSlugServicesRoute: OrgSlugServicesRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRoute,
  OrgSlugTeamRoute: OrgSlugTeamRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  CatalogSlugRoute: CatalogSlugRouteWithChildren,
  OrgSlugRoute: OrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
