
import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, Link } from '@tanstack/react-router';
import { Invoice, InvoiceStatus, InvoiceTransfer } from '@/types';
import { getInvoices, updateInvoiceStatus, transferInvoiceOwnership, getInvoiceLineage, getInvoiceTransfers } from '@/services/storage';
import { Button, Card, Badge, Input, Select } from '@/components/ui';
import { Plus, Eye, Copy, Send, Sparkles, X, CheckSquare, Square, Mail, DollarSign, Link as LinkIcon, ArrowRightLeft, Search, RotateCcw, ChevronLeft, ChevronRight, User, Building2, GitBranch, ArrowRight, TrendingUp, TrendingDown } from 'lucide-react';
import { sendInvoiceEmail } from '@/services/email';
import { generateInvoiceEmailBody } from '@/services/geminiService';
import { useAdminContext } from './AdminLayout';
import { useTranslation } from '@/hooks/useTranslation';
import { usePrompt } from '@/context/PromptContext';

const Invoices: React.FC = () => {
    const { org, formatMoney } = useAdminContext();
    const navigate = useNavigate();
    const prompt = usePrompt();
    const translationStrings = useMemo(() => ([
        'Invoices',
        'Create Invoice',
        'Selected',
        'Mark Paid',
        'Send Email',
        'Invoice #',
        'Client',
        'Date',
        'Total',
        'Status',
        'Actions',
        'No invoices found.',
        'Due:',
        'Overdue',
        'days',
        'Due today',
        'Due in',
        'Send Invoice',
        'Email Message',
        'AI Generating...',
        'Drafting email...',
        'Generated by Gemini AI. Feel free to edit before sending.',
        'Cancel',
        'Send Email',
        'Invoice link copied to clipboard!',
        'Copy Public Link',
        'Duplicate',
        'View/Print',
        'Send Email',
        'Mark invoices as paid?',
        'Send emails for invoices?',
        'Failed to send email.',
        'Some emails failed to send.',
        'Search by client or invoice #',
        'All Statuses',
        'Filter by Status',
        'From Date',
        'To Date',
        'Clear Filters',
        'Showing',
        'to',
        'of',
        'results',
        'Previous',
        'Next',
        'Page',
        'Transfer Ownership',
        'Transfer this invoice to a new owner (resale)',
        'Current Owner',
        'New Owner Details',
        'New Owner Name',
        'New Owner Email',
        'New Owner Company',
        'Transfer Reason',
        'e.g. Item resold to new owner',
        'Transfer',
        'Previously owned by',
        'Ownership transferred successfully!',
        'Failed to transfer ownership.',
        'Please enter new owner name',
        'New Price (Optional)',
        'Leave empty to keep same price',
        'View Lineage',
        'Invoice Lineage',
        'Transfer History',
        'Original',
        'Transferred',
        'Price Change',
        'Close',
        'No transfer history',
    ]), []);
    const { t } = useTranslation(translationStrings);
    const [invoices, setInvoices] = useState<Invoice[]>([]);

    // Filter State
    const [searchQuery, setSearchQuery] = useState('');
    const [statusFilter, setStatusFilter] = useState('ALL');
    const [dateRange, setDateRange] = useState({ start: '', end: '' });

    const filteredInvoices = useMemo(() => {
        return invoices.filter(invoice => {
            const matchesSearch = !searchQuery || (
                (invoice.clientName || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
                (invoice.invoiceNumber || '').toLowerCase().includes(searchQuery.toLowerCase())
            );
            
            const matchesStatus = statusFilter === 'ALL' || invoice.status === statusFilter;
            
            let matchesDate = true;
            if (dateRange.start) {
                matchesDate = matchesDate && new Date(invoice.date) >= new Date(dateRange.start);
            }
            if (dateRange.end) {
                const end = new Date(dateRange.end);
                end.setHours(23, 59, 59, 999);
                matchesDate = matchesDate && new Date(invoice.date) <= end;
            }

            return matchesSearch && matchesStatus && matchesDate;
        });
    }, [invoices, searchQuery, statusFilter, dateRange]);

    // Pagination State
    const [currentPage, setCurrentPage] = useState(1);
    const itemsPerPage = 10;

    // Reset page on filter change
    useEffect(() => {
        setCurrentPage(1);
    }, [searchQuery, statusFilter, dateRange]);

    const totalPages = Math.ceil(filteredInvoices.length / itemsPerPage);
    const paginatedInvoices = useMemo(() => {
        const start = (currentPage - 1) * itemsPerPage;
        return filteredInvoices.slice(start, start + itemsPerPage);
    }, [filteredInvoices, currentPage]);

    // Bulk Selection State
    const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

    // Send Modal State
    const [sendingInvoice, setSendingInvoice] = useState<Invoice | null>(null);
    const [emailBody, setEmailBody] = useState('');
    const [isGeneratingEmail, setIsGeneratingEmail] = useState(false);
    const [isSending, setIsSending] = useState(false);
    const [isBulkProcessing, setIsBulkProcessing] = useState(false);

    const [transferringInvoice, setTransferringInvoice] = useState<Invoice | null>(null);
    const [newOwnerName, setNewOwnerName] = useState('');
    const [newOwnerEmail, setNewOwnerEmail] = useState('');
    const [newOwnerCompany, setNewOwnerCompany] = useState('');
    const [newOwnerTin, setNewOwnerTin] = useState('');
    const [newPrice, setNewPrice] = useState('');
    const [transferReason, setTransferReason] = useState('');
    const [isTransferring, setIsTransferring] = useState(false);

    const [lineageInvoice, setLineageInvoice] = useState<Invoice | null>(null);
    const [lineageData, setLineageData] = useState<Invoice[]>([]);
    const [transferData, setTransferData] = useState<InvoiceTransfer[]>([]);
    const [isLoadingLineage, setIsLoadingLineage] = useState(false);

    const loadInvoices = () => {
        if (org) getInvoices(org.id).then(setInvoices);
    };

    useEffect(() => {
        loadInvoices();
    }, [org]);

    // Bulk Selection Handlers
    const toggleSelectAll = () => {
        if (selectedIds.size === filteredInvoices.length && filteredInvoices.length > 0) {
            setSelectedIds(new Set());
        } else {
            setSelectedIds(new Set(filteredInvoices.map(i => i.id)));
        }
    };

    const toggleSelect = (id: string) => {
        const newSet = new Set(selectedIds);
        if (newSet.has(id)) {
            newSet.delete(id);
        } else {
            newSet.add(id);
        }
        setSelectedIds(newSet);
    };

    const handleBulkMarkPaid = async () => {
        const confirmed = await prompt.confirm(`${t('Mark invoices as paid?')} (${selectedIds.size})`);
        if (!confirmed) return;
        setIsBulkProcessing(true);
        await Promise.all(Array.from(selectedIds).map(id => updateInvoiceStatus(id, InvoiceStatus.PAID)));
        setIsBulkProcessing(false);
        setSelectedIds(new Set());
        loadInvoices();
    };

    const handleBulkSendReminders = async () => {
        const confirmed = await prompt.confirm(`${t('Send emails for invoices?')} (${selectedIds.size})`);
        if (!confirmed) return;
        setIsBulkProcessing(true);
        const selectedInvoices = invoices.filter(i => selectedIds.has(i.id));
        const failedInvoices: string[] = [];

        for (const invoice of selectedInvoices) {
            try {
                await sendInvoiceEmail(invoice, { orgName: org.name });
                if (invoice.status === InvoiceStatus.DRAFT) {
                    await updateInvoiceStatus(invoice.id, InvoiceStatus.SENT);
                }
            } catch (error) {
                console.error(error);
                failedInvoices.push(invoice.invoiceNumber);
            }
        }

        setIsBulkProcessing(false);
        setSelectedIds(new Set());
        loadInvoices();
        if (failedInvoices.length > 0) {
            prompt.alert({ message: `${t('Some emails failed to send.')} (${failedInvoices.join(', ')})`, type: 'warning' });
        }
    };

    const openSendModal = async (invoice: Invoice) => {
        setSendingInvoice(invoice);
        setIsGeneratingEmail(true);

        const formattedTotal = formatMoney(invoice.total);
        const dueDate = new Date(invoice.dueDate).toLocaleDateString();

        const generatedText = await generateInvoiceEmailBody(
            invoice.clientName,
            invoice.invoiceNumber,
            formattedTotal,
            dueDate
        );

        setEmailBody(generatedText);
        setIsGeneratingEmail(false);
    };

    const confirmSend = async () => {
        if (!sendingInvoice) return;
        setIsSending(true);
        try {
            await sendInvoiceEmail(sendingInvoice, { body: emailBody, orgName: org.name });
            await updateInvoiceStatus(sendingInvoice.id, InvoiceStatus.SENT);
            setSendingInvoice(null);
            loadInvoices();
        } catch (error) {
            console.error(error);
            prompt.alert({ message: t('Failed to send email.'), type: 'error' });
        } finally {
            setIsSending(false);
        }
    };

    const handleTransferOwnership = async () => {
        if (!transferringInvoice || !newOwnerName.trim()) {
            prompt.alert({ message: t('Please enter new owner name'), type: 'warning' });
            return;
        }
        setIsTransferring(true);
        try {
            const parsedPrice = newPrice ? parseFloat(newPrice) : undefined;
            await transferInvoiceOwnership(
                transferringInvoice.id,
                {
                    name: newOwnerName.trim(),
                    email: newOwnerEmail.trim() || transferringInvoice.clientEmail,
                    company: newOwnerCompany.trim() || undefined,
                    tin: newOwnerTin.trim() || undefined,
                },
                transferReason.trim() || undefined,
                parsedPrice
            );
            setTransferringInvoice(null);
            setNewOwnerName('');
            setNewOwnerEmail('');
            setNewOwnerCompany('');
            setNewOwnerTin('');
            setNewPrice('');
            setTransferReason('');
            loadInvoices();
            prompt.alert({ message: t('Ownership transferred successfully!'), type: 'success' });
        } catch (error) {
            console.error(error);
            prompt.alert({ message: t('Failed to transfer ownership.'), type: 'error' });
        } finally {
            setIsTransferring(false);
        }
    };

    const openLineageModal = async (invoice: Invoice) => {
        setLineageInvoice(invoice);
        setIsLoadingLineage(true);
        try {
            const rootId = invoice.rootInvoiceId || invoice.id;
            const [lineage, transfers] = await Promise.all([
                getInvoiceLineage(invoice.id),
                getInvoiceTransfers(rootId),
            ]);
            setLineageData(lineage);
            setTransferData(transfers);
        } catch (error) {
            console.error(error);
            setLineageData([]);
            setTransferData([]);
        } finally {
            setIsLoadingLineage(false);
        }
    };

    const getDueAlert = (invoice: Invoice) => {
        if (invoice.status === InvoiceStatus.PAID) return null;
        if (!invoice.dueDate) return null;

        const due = new Date(invoice.dueDate);
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        due.setHours(0, 0, 0, 0);

        const diffTime = due.getTime() - today.getTime();
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

        if (diffDays < 0) {
            return (
                <span className="inline-flex items-center mt-2 px-2 py-1 rounded-md text-[10px] font-bold bg-red-500/10 text-red-500 border border-red-500/20">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mr-1.5 animate-pulse"></span>
                    {t('Overdue')} {Math.abs(diffDays)} {t('days')}
                </span>
            );
        }

        if (diffDays >= 0 && diffDays <= 3) {
            return (
                <span className="inline-flex items-center mt-2 px-2 py-1 rounded-md text-[10px] font-bold bg-amber-500/10 text-amber-500 border border-amber-500/20">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mr-1.5"></span>
                    {diffDays === 0 ? t('Due today') : `${t('Due in')} ${diffDays} ${t('days')}`}
                </span>
            );
        }
        return null;
    };

    if (!org.id) return <div className="p-8">Loading...</div>;
    return (
        <div className="space-y-6 relative">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-foreground">{t('Invoices')}</h2>
                <Button onClick={() => navigate({ to: '/org/$slug/invoices/create', params: { slug: org.slug } })}>
                    <Plus className="w-4 h-4 mr-2" /> {t('Create Invoice')}
                </Button>
            </div>

            {/* Bulk Action Bar */}
            {selectedIds.size > 0 && (
                <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-40 bg-surface text-foreground px-4 py-3 rounded-full shadow-xl border border-border flex items-center gap-4 animate-fade-in-up backdrop-blur-md">
                    <span className="text-sm font-semibold pl-2">{selectedIds.size} {t('Selected')}</span>
                    <div className="h-4 w-px bg-border"></div>
                    <button
                        onClick={handleBulkMarkPaid}
                        disabled={isBulkProcessing}
                        className="flex items-center gap-2 text-xs hover:text-green-500 transition-colors disabled:opacity-50"
                    >
                        <DollarSign className="w-4 h-4" /> {t('Mark Paid')}
                    </button>
                    <button
                        onClick={handleBulkSendReminders}
                        disabled={isBulkProcessing}
                        className="flex items-center gap-2 text-xs hover:text-primary transition-colors disabled:opacity-50"
                    >
                        <Mail className="w-4 h-4" /> {t('Send Email')}
                    </button>
                    <button
                        onClick={() => setSelectedIds(new Set())}
                        className="ml-2 p-1 hover:bg-surface/80 rounded-full"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>
            )}

            {/* Filters */}
            <div className="flex flex-col md:flex-row gap-4 mb-6 items-end">
                <div className="relative flex-1 w-full md:max-w-md">
                    <Input
                        placeholder={t('Search by client or invoice #')}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="pl-10 border border-border text-sm placeholder:text-xs"
                    />
                    <div className="absolute top-1/2 left-3 -translate-y-1/2 text-muted pointer-events-none">
                        <Search className="w-4 h-4" />
                    </div>
                </div>
                <div className="w-full md:w-48">
                    <Select
                        options={[
                            { label: t('All Statuses'), value: 'ALL' },
                            { label: t('Paid'), value: 'PAID' },
                            { label: t('Sent'), value: 'SENT' },
                            { label: t('Draft'), value: 'DRAFT' },
                            { label: t('Overdue'), value: 'OVERDUE' },
                        ]}
                        value={statusFilter}
                        onChange={(e) => setStatusFilter(e.target.value)}
                    />
                </div>
                <div className="w-full md:w-auto flex gap-2">
                   <div className="w-full md:w-40">
                        <Input 
                            type="date" 
                            value={dateRange.start}
                            onChange={(e) => setDateRange(prev => ({ ...prev, start: e.target.value }))}
                        />
                   </div>
                   <div className="w-full md:w-40">
                        <Input 
                            type="date" 
                            value={dateRange.end}
                            onChange={(e) => setDateRange(prev => ({ ...prev, end: e.target.value }))}
                        />
                   </div>
                </div>
                <Button variant="ghost" onClick={() => { setSearchQuery(''); setStatusFilter('ALL'); setDateRange({ start: '', end: '' }); }} title={t('Clear Filters')}>
                    <RotateCcw className="w-4 h-4" />
                </Button>
            </div>

            <Card className="overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="bg-surface/50 border-b border-border">
                            <tr>
                                <th className="px-6 py-4 w-10">
                                    <button onClick={toggleSelectAll} className="flex items-center text-muted hover:text-foreground">
                                        {filteredInvoices.length > 0 && selectedIds.size === filteredInvoices.length ?
                                            <CheckSquare className="w-4 h-4 text-primary" /> :
                                            <Square className="w-4 h-4" />
                                        }
                                    </button>
                                </th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Invoice #')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Client')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Date')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Total')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Status')}</th>
                                <th className="px-6 py-4 font-medium text-muted text-right">{t('Actions')}</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-border">
                            {filteredInvoices.length === 0 ? (
                                <tr><td colSpan={7} className="text-center py-8 text-muted">{t('No invoices found.')}</td></tr>
                            ) : (
                                paginatedInvoices.map(invoice => (
                                    <tr key={invoice.id} className={`hover:bg-surface/50 ${selectedIds.has(invoice.id) ? 'bg-primary/5' : ''}`}>
                                        <td className="px-6 py-4">
                                            <button onClick={() => toggleSelect(invoice.id)} className="flex items-center text-muted hover:text-foreground">
                                                {selectedIds.has(invoice.id) ?
                                                    <CheckSquare className="w-4 h-4 text-primary" /> :
                                                    <Square className="w-4 h-4" />
                                                }
                                            </button>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2">
                                                <span className="font-mono font-medium text-foreground">{invoice.invoiceNumber}</span>
                                                {(invoice.parentInvoiceId || invoice.rootInvoiceId) && (
                                                    <button
                                                        onClick={() => openLineageModal(invoice)}
                                                        className="flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium bg-purple-500/10 text-purple-500 rounded border border-purple-500/20 hover:bg-purple-500/20 transition-colors"
                                                        title={t('View Lineage')}
                                                    >
                                                        <GitBranch className="w-3 h-3" />
                                                        #{invoice.transferSequence || 1}
                                                    </button>
                                                )}
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="font-medium text-foreground">{invoice.clientName}</div>
                                            <div className="text-xs text-muted">{invoice.clientEmail}</div>
                                        </td>
                                        <td className="px-6 py-4 text-muted">
                                            <div>{new Date(invoice.date).toLocaleDateString()}</div>
                                            <div className="text-xs text-muted/70 mt-0.5">{t('Due:')} {new Date(invoice.dueDate).toLocaleDateString()}</div>
                                        </td>
                                        <td className="px-6 py-4 font-medium text-foreground">{formatMoney(invoice.total)}</td>
                                        <td className="px-6 py-4">
                                            <Badge status={invoice.status} />
                                            {getDueAlert(invoice)}
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="flex items-center justify-end gap-2">
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-primary/50 text-foreground"
                                                    title={t('Send Email')}
                                                    onClick={() => openSendModal(invoice)}
                                                >
                                                    <Send className="w-4 h-4" />
                                                </Button>
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-secondary/50 text-foreground"
                                                    title={t('Copy Public Link')}
                                                    onClick={() => {
                                                        const url = `${window.location.origin}/#/catalog/${org.slug}/invoice/${invoice.id}`;
                                                        navigator.clipboard.writeText(url);
                                                        prompt.alert({ message: t('Invoice link copied to clipboard!'), type: 'success' });
                                                    }}
                                                >
                                                    <LinkIcon className="w-4 h-4" />
                                                </Button>
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-primary/50 text-foreground"
                                                    title={t('Transfer Ownership')}
                                                    onClick={() => {
                                                        setTransferringInvoice(invoice);
                                                        setNewOwnerName('');
                                                        setNewOwnerEmail('');
                                                        setNewOwnerCompany('');
                                                        setNewOwnerTin('');
                                                        setNewPrice('');
                                                        setTransferReason('');
                                                    }}
                                                >
                                                    <ArrowRightLeft className="w-4 h-4" />
                                                </Button>
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-foreground/50 text-foreground"
                                                    title={t('Duplicate')}
                                                    onClick={() => navigate({ to: '/org/$slug/invoices/create', params: { slug: org.slug }, state: { duplicateInvoice: invoice } as any })}
                                                >
                                                    <Copy className="w-4 h-4" />
                                                </Button>
                                                <Link to="/catalog/$slug/invoice/$invoiceId" params={{ slug: org.slug, invoiceId: invoice.id }} target="_blank">
                                                    <Button variant="ghost" className="h-8 w-8 p-0 border-border hover:border-foreground/50 text-foreground" title={t('View/Print')}>
                                                        <Eye className="w-4 h-4" />
                                                    </Button>
                                                </Link>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </Card>

            {/* Pagination */}
            {filteredInvoices.length > 0 && (
                <div className="flex items-center justify-between px-2">
                    <div className="text-sm text-muted">
                        {t('Showing')} <span className="font-medium text-foreground">{Math.min(filteredInvoices.length, (currentPage - 1) * itemsPerPage + 1)}</span> {t('to')} <span className="font-medium text-foreground">{Math.min(filteredInvoices.length, currentPage * itemsPerPage)}</span> {t('of')} <span className="font-medium text-foreground">{filteredInvoices.length}</span> {t('results')}
                    </div>
                    <div className="flex items-center gap-2">
                        <Button
                            variant="outline"
                            className="h-8 w-8 p-0"
                            onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                            disabled={currentPage === 1}
                        >
                            <ChevronLeft className="w-4 h-4" />
                        </Button>
                        <div className="text-sm font-medium">
                            {t('Page')} {currentPage} / {totalPages}
                        </div>
                        <Button
                            variant="outline"
                            className="h-8 w-8 p-0"
                            onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                            disabled={currentPage === totalPages}
                        >
                            <ChevronRight className="w-4 h-4" />
                        </Button>
                    </div>
                </div>
            )}

            {/* Send Email Modal */}
            {sendingInvoice && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
                    <Card className="w-full max-w-lg p-6 relative animate-fade-in-up">
                        <button
                            onClick={() => setSendingInvoice(null)}
                            className="absolute top-4 right-4 text-muted hover:text-foreground"
                        >
                            <X className="w-5 h-5" />
                        </button>

                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2 text-foreground">
                            <Send className="w-4 h-4 text-primary" />
                            {t('Send Invoice')} {sendingInvoice.invoiceNumber}
                        </h3>

                        <div className="mb-4">
                            <label className="text-sm font-medium text-muted mb-2 block flex justify-between">
                                <span>{t('Email Message')}</span>
                                {isGeneratingEmail && <span className="text-xs text-primary flex items-center"><Sparkles className="w-3 h-3 mr-1 animate-spin" /> {t('AI Generating...')}</span>}
                            </label>
                            <textarea
                                className="w-full h-40 resize-none rounded-lg border border-border bg-surface px-4 py-2 text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-2 focus:ring-primary/30 transition-all duration-200"
                                value={emailBody}
                                onChange={(e) => setEmailBody(e.target.value)}
                                placeholder={t('Drafting email...')}
                            />
                            <p className="text-xs text-muted mt-2">
                                <Sparkles className="w-3 h-3 inline mr-1" />
                                {t('Generated by Gemini AI. Feel free to edit before sending.')}
                            </p>
                        </div>

                        <div className="flex gap-3 justify-end">
                            <Button variant="outline" onClick={() => setSendingInvoice(null)}>{t('Cancel')}</Button>
                            <Button onClick={confirmSend} isLoading={isSending}>{t('Send Email')}</Button>
                        </div>
                    </Card>
                </div>
            )}

            {transferringInvoice && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
                    <Card className="w-full max-w-lg p-6 relative animate-fade-in-up">
                        <button
                            onClick={() => setTransferringInvoice(null)}
                            className="absolute top-4 right-4 text-muted hover:text-foreground"
                        >
                            <X className="w-5 h-5" />
                        </button>

                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2 text-foreground">
                            <ArrowRightLeft className="w-5 h-5 text-primary" />
                            {t('Transfer Ownership')}
                        </h3>
                        <p className="text-sm text-muted mb-6">{t('Transfer this invoice to a new owner (resale)')}</p>

                        <div className="mb-5 p-4 rounded-xl bg-primary/10 border border-primary/20">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center">
                                    <User className="w-5 h-5 text-primary" />
                                </div>
                                <div className="flex-1">
                                    <p className="text-xs text-primary font-semibold uppercase tracking-wide">{t('Current Owner')}</p>
                                    <p className="text-sm font-bold text-foreground">{transferringInvoice.clientName}</p>
                                    <p className="text-xs text-muted">{transferringInvoice.clientEmail}</p>
                                </div>
                                <div className="text-right">
                                    <div className="text-xs text-muted">{t('Invoice #')}</div>
                                    <div className="font-mono font-bold text-sm text-foreground">{transferringInvoice.invoiceNumber}</div>
                                </div>
                            </div>
                        </div>

                        <div className="mb-5 p-4 rounded-xl bg-surface border border-border">
                            <p className="text-xs text-foreground font-semibold uppercase tracking-wide mb-3 flex items-center gap-2">
                                <Building2 className="w-4 h-4 text-primary" />
                                {t('New Owner Details')}
                            </p>
                            <div className="space-y-3">
                                <Input
                                    label={t('New Owner Name')}
                                    value={newOwnerName}
                                    onChange={(e) => setNewOwnerName(e.target.value)}
                                    placeholder="John Doe"
                                />
                                <Input
                                    label={t('New Owner Email')}
                                    type="email"
                                    value={newOwnerEmail}
                                    onChange={(e) => setNewOwnerEmail(e.target.value)}
                                    placeholder="john@example.com"
                                />
                                <Input
                                    label={t('New Owner Company')}
                                    value={newOwnerCompany}
                                    onChange={(e) => setNewOwnerCompany(e.target.value)}
                                    placeholder="Optional"
                                />
                                <Input
                                    label={t('New Price (Optional)')}
                                    type="number"
                                    step="0.01"
                                    value={newPrice}
                                    onChange={(e) => setNewPrice(e.target.value)}
                                    placeholder={t('Leave empty to keep same price')}
                                />
                            </div>
                        </div>

                        <div className="mb-6">
                            <label className="text-sm font-medium text-foreground mb-2 block">
                                {t('Transfer Reason')}
                            </label>
                            <textarea
                                className="w-full h-16 resize-none rounded-lg border border-border bg-surface px-4 py-2 text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-2 focus:ring-primary/30 transition-all duration-200"
                                value={transferReason}
                                onChange={(e) => setTransferReason(e.target.value)}
                                placeholder={t('e.g. Item resold to new owner')}
                            />
                        </div>

                        <div className="flex gap-3 justify-end">
                            <Button variant="outline" onClick={() => setTransferringInvoice(null)}>{t('Cancel')}</Button>
                            <Button
                                onClick={handleTransferOwnership}
                                isLoading={isTransferring}
                                disabled={!newOwnerName.trim()}
                                className="bg-primary hover:bg-primary/90 text-white border-none"
                            >
                                <ArrowRightLeft className="w-4 h-4 mr-2" />
                                {t('Transfer')}
                            </Button>
                        </div>
                    </Card>
                </div>
            )}

            {lineageInvoice && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
                    <Card className="w-full max-w-2xl p-6 relative animate-fade-in-up max-h-[90vh] overflow-y-auto">
                        <button
                            onClick={() => setLineageInvoice(null)}
                            className="absolute top-4 right-4 text-muted hover:text-foreground"
                        >
                            <X className="w-5 h-5" />
                        </button>

                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2 text-foreground">
                            <GitBranch className="w-5 h-5 text-purple-500" />
                            {t('Invoice Lineage')}
                        </h3>

                        {isLoadingLineage ? (
                            <div className="py-8 text-center text-muted">Loading...</div>
                        ) : (
                            <div className="space-y-6">
                                <div className="space-y-3">
                                    {lineageData.map((inv, idx) => (
                                        <div
                                            key={inv.id}
                                            className={`p-4 rounded-xl border transition-all ${
                                                inv.id === lineageInvoice.id
                                                    ? 'border-primary bg-primary/5'
                                                    : 'border-border bg-surface'
                                            }`}
                                        >
                                            <div className="flex items-center justify-between">
                                                <div className="flex items-center gap-3">
                                                    <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${
                                                        idx === 0
                                                            ? 'bg-green-500/20 text-green-500'
                                                            : 'bg-purple-500/20 text-purple-500'
                                                    }`}>
                                                        {idx === 0 ? t('Original').charAt(0) : `#${inv.transferSequence || idx}`}
                                                    </div>
                                                    <div>
                                                        <div className="font-mono font-medium text-sm">{inv.invoiceNumber}</div>
                                                        <div className="text-xs text-muted">{inv.clientName}</div>
                                                    </div>
                                                </div>
                                                <div className="text-right">
                                                    <div className="font-medium">{formatMoney(inv.total)}</div>
                                                    <div className="text-xs text-muted">{new Date(inv.date).toLocaleDateString()}</div>
                                                </div>
                                            </div>
                                        </div>
                                    ))}
                                </div>

                                {transferData.length > 0 && (
                                    <div>
                                        <h4 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
                                            <ArrowRightLeft className="w-4 h-4 text-primary" />
                                            {t('Transfer History')}
                                        </h4>
                                        <div className="space-y-2">
                                            {transferData.map((transfer) => (
                                                <div key={transfer.id} className="p-3 rounded-lg bg-surface border border-border">
                                                    <div className="flex items-center gap-2 text-sm mb-2">
                                                        <span className="font-medium">{transfer.fromClientName}</span>
                                                        <ArrowRight className="w-4 h-4 text-muted" />
                                                        <span className="font-medium">{transfer.toClientName}</span>
                                                    </div>
                                                    <div className="flex items-center justify-between text-xs">
                                                        <span className="text-muted">
                                                            {new Date(transfer.transferredAt).toLocaleDateString()}
                                                        </span>
                                                        <div className="flex items-center gap-2">
                                                            <span className="text-muted">{formatMoney(transfer.originalAmount)}</span>
                                                            <ArrowRight className="w-3 h-3 text-muted" />
                                                            <span className="font-medium">{formatMoney(transfer.newAmount)}</span>
                                                            {transfer.priceDelta !== 0 && (
                                                                <span className={`flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] font-medium ${
                                                                    transfer.priceDelta > 0
                                                                        ? 'bg-green-500/10 text-green-500'
                                                                        : 'bg-red-500/10 text-red-500'
                                                                }`}>
                                                                    {transfer.priceDelta > 0 ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
                                                                    {transfer.priceDelta > 0 ? '+' : ''}{formatMoney(transfer.priceDelta)}
                                                                </span>
                                                            )}
                                                        </div>
                                                    </div>
                                                    {transfer.reason && (
                                                        <div className="text-xs text-muted mt-2 italic">"{transfer.reason}"</div>
                                                    )}
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}

                                {transferData.length === 0 && lineageData.length <= 1 && (
                                    <p className="text-center text-muted py-4">{t('No transfer history')}</p>
                                )}
                            </div>
                        )}

                        <div className="mt-6 flex justify-end">
                            <Button variant="outline" onClick={() => setLineageInvoice(null)}>
                                {t('Close')}
                            </Button>
                        </div>
                    </Card>
                </div>
            )}
        </div>
    );
};

export default Invoices;
