
import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, Link } from '@tanstack/react-router';
import { Invoice, InvoiceStatus } from '@/types';
import { getInvoices, updateInvoiceStatus } from '@/services/storage';
import { Button, Card, Badge } from '@/components/ui';
import { Plus, Eye, Copy, Send, Sparkles, X, CheckSquare, Square, Mail, DollarSign, Link as LinkIcon } from 'lucide-react';
import { sendInvoiceEmail } from '@/services/email';
import { generateInvoiceEmailBody } from '@/services/geminiService';
import { useAdminContext } from './AdminLayout';
import { useTranslation } from '@/hooks/useTranslation';

const Invoices: React.FC = () => {
    const { org, formatMoney } = useAdminContext();
    const navigate = useNavigate();
    const translationStrings = useMemo(() => ([
        'Invoices',
        'Create Invoice',
        'Selected',
        'Mark Paid',
        'Send Email',
        'Invoice #',
        'Client',
        'Date',
        'Total',
        'Status',
        'Actions',
        'No invoices found.',
        'Due:',
        'Overdue',
        'days',
        'Due today',
        'Due in',
        'Send Invoice',
        'Email Message',
        'AI Generating...',
        'Drafting email...',
        'Generated by Gemini AI. Feel free to edit before sending.',
        'Cancel',
        'Send Email',
        'Invoice link copied to clipboard!',
        'Copy Public Link',
        'Duplicate',
        'View/Print',
        'Send Email',
        'Mark invoices as paid?',
        'Send emails for invoices?',
        'Failed to send email.',
        'Some emails failed to send.',
    ]), []);
    const { t } = useTranslation(translationStrings);
    const [invoices, setInvoices] = useState<Invoice[]>([]);

    // Bulk Selection State
    const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

    // Send Modal State
    const [sendingInvoice, setSendingInvoice] = useState<Invoice | null>(null);
    const [emailBody, setEmailBody] = useState('');
    const [isGeneratingEmail, setIsGeneratingEmail] = useState(false);
    const [isSending, setIsSending] = useState(false);
    const [isBulkProcessing, setIsBulkProcessing] = useState(false);

    const loadInvoices = () => {
        if (org) getInvoices(org.id).then(setInvoices);
    };

    useEffect(() => {
        loadInvoices();
    }, [org]);

    // Bulk Selection Handlers
    const toggleSelectAll = () => {
        if (selectedIds.size === invoices.length) {
            setSelectedIds(new Set());
        } else {
            setSelectedIds(new Set(invoices.map(i => i.id)));
        }
    };

    const toggleSelect = (id: string) => {
        const newSet = new Set(selectedIds);
        if (newSet.has(id)) {
            newSet.delete(id);
        } else {
            newSet.add(id);
        }
        setSelectedIds(newSet);
    };

    const handleBulkMarkPaid = async () => {
        if (!confirm(`${t('Mark invoices as paid?')} (${selectedIds.size})`)) return;
        setIsBulkProcessing(true);
        await Promise.all(Array.from(selectedIds).map(id => updateInvoiceStatus(id, InvoiceStatus.PAID)));
        setIsBulkProcessing(false);
        setSelectedIds(new Set());
        loadInvoices();
    };

    const handleBulkSendReminders = async () => {
        if (!confirm(`${t('Send emails for invoices?')} (${selectedIds.size})`)) return;
        setIsBulkProcessing(true);
        const selectedInvoices = invoices.filter(i => selectedIds.has(i.id));
        const failedInvoices: string[] = [];

        for (const invoice of selectedInvoices) {
            try {
                await sendInvoiceEmail(invoice, { orgName: org.name });
                if (invoice.status === InvoiceStatus.DRAFT) {
                    await updateInvoiceStatus(invoice.id, InvoiceStatus.SENT);
                }
            } catch (error) {
                console.error(error);
                failedInvoices.push(invoice.invoiceNumber);
            }
        }

        setIsBulkProcessing(false);
        setSelectedIds(new Set());
        loadInvoices();
        if (failedInvoices.length > 0) {
            alert(`${t('Some emails failed to send.')} (${failedInvoices.join(', ')})`);
        }
    };

    const openSendModal = async (invoice: Invoice) => {
        setSendingInvoice(invoice);
        setIsGeneratingEmail(true);

        const formattedTotal = formatMoney(invoice.total);
        const dueDate = new Date(invoice.dueDate).toLocaleDateString();

        const generatedText = await generateInvoiceEmailBody(
            invoice.clientName,
            invoice.invoiceNumber,
            formattedTotal,
            dueDate
        );

        setEmailBody(generatedText);
        setIsGeneratingEmail(false);
    };

    const confirmSend = async () => {
        if (!sendingInvoice) return;
        setIsSending(true);
        try {
            await sendInvoiceEmail(sendingInvoice, { body: emailBody, orgName: org.name });
            await updateInvoiceStatus(sendingInvoice.id, InvoiceStatus.SENT);
            setSendingInvoice(null);
            loadInvoices();
        } catch (error) {
            console.error(error);
            alert(t('Failed to send email.'));
        } finally {
            setIsSending(false);
        }
    };

    const getDueAlert = (invoice: Invoice) => {
        if (invoice.status === InvoiceStatus.PAID) return null;
        if (!invoice.dueDate) return null;

        const due = new Date(invoice.dueDate);
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        due.setHours(0, 0, 0, 0);

        const diffTime = due.getTime() - today.getTime();
        const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

        if (diffDays < 0) {
            return (
                <span className="inline-flex items-center mt-2 px-2 py-1 rounded-md text-[10px] font-bold bg-red-500/10 text-red-500 border border-red-500/20">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-500 mr-1.5 animate-pulse"></span>
                    {t('Overdue')} {Math.abs(diffDays)} {t('days')}
                </span>
            );
        }

        if (diffDays >= 0 && diffDays <= 3) {
            return (
                <span className="inline-flex items-center mt-2 px-2 py-1 rounded-md text-[10px] font-bold bg-amber-500/10 text-amber-500 border border-amber-500/20">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mr-1.5"></span>
                    {diffDays === 0 ? t('Due today') : `${t('Due in')} ${diffDays} ${t('days')}`}
                </span>
            );
        }
        return null;
    };

    if (!org.id) return <div className="p-8">Loading...</div>;
    return (
        <div className="space-y-6 relative">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-foreground">{t('Invoices')}</h2>
                <Button onClick={() => navigate({ to: '/org/$slug/invoices/create', params: { slug: org.slug } })}>
                    <Plus className="w-4 h-4 mr-2" /> {t('Create Invoice')}
                </Button>
            </div>

            {/* Bulk Action Bar */}
            {selectedIds.size > 0 && (
                <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-40 bg-surface text-foreground px-4 py-3 rounded-full shadow-xl border border-border flex items-center gap-4 animate-fade-in-up backdrop-blur-md">
                    <span className="text-sm font-semibold pl-2">{selectedIds.size} {t('Selected')}</span>
                    <div className="h-4 w-px bg-border"></div>
                    <button
                        onClick={handleBulkMarkPaid}
                        disabled={isBulkProcessing}
                        className="flex items-center gap-2 text-xs hover:text-green-500 transition-colors disabled:opacity-50"
                    >
                        <DollarSign className="w-4 h-4" /> {t('Mark Paid')}
                    </button>
                    <button
                        onClick={handleBulkSendReminders}
                        disabled={isBulkProcessing}
                        className="flex items-center gap-2 text-xs hover:text-primary transition-colors disabled:opacity-50"
                    >
                        <Mail className="w-4 h-4" /> {t('Send Email')}
                    </button>
                    <button
                        onClick={() => setSelectedIds(new Set())}
                        className="ml-2 p-1 hover:bg-surface/80 rounded-full"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>
            )}

            <Card className="overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="bg-surface/50 border-b border-border">
                            <tr>
                                <th className="px-6 py-4 w-10">
                                    <button onClick={toggleSelectAll} className="flex items-center text-muted hover:text-foreground">
                                        {invoices.length > 0 && selectedIds.size === invoices.length ?
                                            <CheckSquare className="w-4 h-4 text-primary" /> :
                                            <Square className="w-4 h-4" />
                                        }
                                    </button>
                                </th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Invoice #')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Client')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Date')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Total')}</th>
                                <th className="px-6 py-4 font-medium text-muted">{t('Status')}</th>
                                <th className="px-6 py-4 font-medium text-muted text-right">{t('Actions')}</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-border">
                            {invoices.length === 0 ? (
                                <tr><td colSpan={7} className="text-center py-8 text-muted">{t('No invoices found.')}</td></tr>
                            ) : (
                                invoices.map(invoice => (
                                    <tr key={invoice.id} className={`hover:bg-surface/50 ${selectedIds.has(invoice.id) ? 'bg-primary/5' : ''}`}>
                                        <td className="px-6 py-4">
                                            <button onClick={() => toggleSelect(invoice.id)} className="flex items-center text-muted hover:text-foreground">
                                                {selectedIds.has(invoice.id) ?
                                                    <CheckSquare className="w-4 h-4 text-primary" /> :
                                                    <Square className="w-4 h-4" />
                                                }
                                            </button>
                                        </td>
                                        <td className="px-6 py-4 font-mono font-medium text-foreground">{invoice.invoiceNumber}</td>
                                        <td className="px-6 py-4">
                                            <div className="font-medium text-foreground">{invoice.clientName}</div>
                                            <div className="text-xs text-muted">{invoice.clientEmail}</div>
                                        </td>
                                        <td className="px-6 py-4 text-muted">
                                            <div>{new Date(invoice.date).toLocaleDateString()}</div>
                                            <div className="text-xs text-muted/70 mt-0.5">{t('Due:')} {new Date(invoice.dueDate).toLocaleDateString()}</div>
                                        </td>
                                        <td className="px-6 py-4 font-medium text-foreground">{formatMoney(invoice.total)}</td>
                                        <td className="px-6 py-4">
                                            <Badge status={invoice.status} />
                                            {getDueAlert(invoice)}
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="flex items-center justify-end gap-2">
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-primary/50 text-foreground"
                                                    title={t('Send Email')}
                                                    onClick={() => openSendModal(invoice)}
                                                >
                                                    <Send className="w-4 h-4" />
                                                </Button>
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-secondary/50 text-foreground"
                                                    title={t('Copy Public Link')}
                                                    onClick={() => {
                                                        const url = `${window.location.origin}/#/catalog/${org.slug}/invoice/${invoice.id}`;
                                                        navigator.clipboard.writeText(url);
                                                        alert(t('Invoice link copied to clipboard!'));
                                                    }}
                                                >
                                                    <LinkIcon className="w-4 h-4" />
                                                </Button>
                                                <Button
                                                    variant="ghost"
                                                    className="h-8 w-8 p-0 border-border hover:border-foreground/50 text-foreground"
                                                    title={t('Duplicate')}
                                                    onClick={() => navigate({ to: '/org/$slug/invoices/create', params: { slug: org.slug }, state: { duplicateInvoice: invoice } as any })}
                                                >
                                                    <Copy className="w-4 h-4" />
                                                </Button>
                                                <Link to="/catalog/$slug/invoice/$invoiceId" params={{ slug: org.slug, invoiceId: invoice.id }} target="_blank">
                                                    <Button variant="ghost" className="h-8 w-8 p-0 border-border hover:border-foreground/50 text-foreground" title={t('View/Print')}>
                                                        <Eye className="w-4 h-4" />
                                                    </Button>
                                                </Link>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </Card>

            {/* Send Email Modal */}
            {sendingInvoice && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
                    <Card className="w-full max-w-lg p-6 relative animate-fade-in-up">
                        <button
                            onClick={() => setSendingInvoice(null)}
                            className="absolute top-4 right-4 text-muted hover:text-foreground"
                        >
                            <X className="w-5 h-5" />
                        </button>

                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2 text-foreground">
                            <Send className="w-4 h-4 text-primary" />
                            {t('Send Invoice')} {sendingInvoice.invoiceNumber}
                        </h3>

                        <div className="mb-4">
                            <label className="text-sm font-medium text-muted mb-2 block flex justify-between">
                                <span>{t('Email Message')}</span>
                                {isGeneratingEmail && <span className="text-xs text-primary flex items-center"><Sparkles className="w-3 h-3 mr-1 animate-spin" /> {t('AI Generating...')}</span>}
                            </label>
                            <textarea
                                className="w-full h-40 resize-none rounded-lg border border-border bg-surface px-4 py-2 text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-2 focus:ring-primary/30 transition-all duration-200"
                                value={emailBody}
                                onChange={(e) => setEmailBody(e.target.value)}
                                placeholder={t('Drafting email...')}
                            />
                            <p className="text-xs text-muted mt-2">
                                <Sparkles className="w-3 h-3 inline mr-1" />
                                {t('Generated by Gemini AI. Feel free to edit before sending.')}
                            </p>
                        </div>

                        <div className="flex gap-3 justify-end">
                            <Button variant="outline" onClick={() => setSendingInvoice(null)}>{t('Cancel')}</Button>
                            <Button onClick={confirmSend} isLoading={isSending}>{t('Send Email')}</Button>
                        </div>
                    </Card>
                </div>
            )}
        </div>
    );
};

export default Invoices;
